// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJE3kEeNJNHAyrp9JY_piefkCSEkZm0I',
    appId: '1:485284708798:web:f9b7c8fe232d5f0e1179ef',
    messagingSenderId: '485284708798',
    projectId: 'moviesandgamesdddg',
    authDomain: 'moviesandgamesdddg.firebaseapp.com',
    storageBucket: 'moviesandgamesdddg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL35FTLjD0owaJH-_GeP8CcyTAQUD28Oo',
    appId: '1:485284708798:android:055178d792bebf741179ef',
    messagingSenderId: '485284708798',
    projectId: 'moviesandgamesdddg',
    storageBucket: 'moviesandgamesdddg.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSXmfq5UEJ2o-5bbLHKieNaBetUkgGxo',
    appId: '1:485284708798:ios:6d156170b07bbcf71179ef',
    messagingSenderId: '485284708798',
    projectId: 'moviesandgamesdddg',
    storageBucket: 'moviesandgamesdddg.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
}
